version: 2
jobs:
  build:
    docker:
      - image: circleci/<language>:ruby:2.4.1
    steps:
      - checkout
      - run: echo "lets test"
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: rake test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
